# Generated by Django 5.1.4 on 2025-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
